### ISSUE TITLE
Is 'apigee-edge-js' missing?

### ISSUE THREAD

**Issue by Lassesen** [DinoChiesa/ApigeeEdge-JWT-Demonstration#3]
I attempted to execute

node ./tools/importAndDeploy -v -o ${ORG} -e ${ENV} -d ./proxy-bundles/jwt-verify
node ./tools/importAndDeploy -v -o ${ORG} -e ${ENV} -d ./proxy-bundles/jwt-verify-goog
node ./tools/importAndDeploy -v -o ${ORG} -e ${ENV} -d ./proxy-bundles/jwt-generate

and get Cannot find module 'apigee-edge-js'

**Comment by DinoChiesa** [comment]
So sorry! 
That apigee-edge-js thing is a node module. 
To get it you must 
```
cd tools
npm install
cd ..
```
Then you can 
```
node ./tools/importAndDeploy -v -o ${ORG} -e ${ENV} -d ./proxy-bundles/jwt-verify
```
and etc. 

I will update the README to state that.  thanks for the feedback.

**Comment by DinoChiesa** [comment]
Fixed.
